project:
  type: website
  resources: 
  - "CNAME"
  
website:
  title: "Active Attack Data Explorer"
  navbar:
    tools:
    logo: "www/alerrt_banner.png"
    right:
      - href: index.qmd #this needs to stay "index.qmd" to be recognized as the landing page
        text: Home
      - href: 1_visuals.qmd
        text: Active Attacks
      - href: 2_victims.qmd
        text: Remembrance
      - href: 3_contact.qmd
        text: Contact
  page-footer: 
    left: "Created by the Research Ring at The ALERRT Center, Texas State University"
    right: 
      - icon: github
        href: "https://github.com/ALERRT-Research/PROJ_activeattack_website"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    
# filters: 
#   - shinylive



