project:
  type: website

website:
  title: "Active Attack Data Explorer"
  navbar:
    logo: "www/alerrt_banner.png"
    right:
      - href: index.qmd #this needs to stay "index.qmd" to be recognized as the landing page
        text: Home
      - href: 1_visuals.qmd
        text: Visualizing Active Attacks
      - href: 2_victims.qmd
        text: Remembrance

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    
filters: 
  - shinylive



